---
- name: Manage certificate for postgreSQL
  ansible.builtin.import_tasks: certificates.yaml
  vars:
    certificate_requests: "{{ db_certificate_requests }}"
  become: true

- name: Install certificate from the default path
  ansible.builtin.file:
    src: >-
      /etc/pki/tls/certs/{{ (db_certificate_requests |
      first)['name'] }}.crt
    dest: /var/lib/pgsql/data/server.crt
    state: link
    owner: postgres
  become: true

- name: Install key from the default path
  ansible.builtin.file:
    src: >-
      /etc/pki/tls/private/{{ (db_certificate_requests |
      first)['name'] }}.key
    dest: /var/lib/pgsql/data/server.key
    state: link
    owner: postgres
  become: true

- name: Configuration de firewalld pour postgreSQL
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.firewall
  vars:
    firewall: "{{ db_firewall }}"
  become: true

- name: Create tempfile for the SQL files
  ansible.builtin.tempfile:
    state: file
  register: temp_keycloak_sql
  delegate_to: localhost

- name: Render SQL files templates to tempfile
  ansible.builtin.template:
    src: "keycloak.sql.j2"
    dest: "{{ temp_keycloak_sql.path }}"
  delegate_to: localhost

- name: Install postgreSQL
  ansible.builtin.import_role:
    name: redhat.rhel_system_roles.postgresql
  become: true

- name: Remove rendered SQL files
  ansible.builtin.file:
    state: absent
    path: "{{ temp_keycloak_sql.path }}"
  delegate_to: localhost
