---
- name: redhat.rhel_system_roles
  version: 1.95.7
- name: ansible.posix
  version: 2.0.0
- name: redhat.runtimes_common
  version: 1.2.2
- name: redhat.rhbk
  version: 3.0.1
- name: community.crypto
